version: "2"
services:
  mapseries:
    build: .
    restart: always
    environment:
      GITHUB_CLIENT_ID: d1b597879ae8454e12a1
      GITHUB_CLIENT_SECRET: 5950b3bdf182ab6df8598846080a9d09b2ed941b
    ports:
      - 8080:8080
      - 8787:8787
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ...:/var/lib/postgresql/data:z
